spring:
  application:
    name: lms-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/lms_db?options=-c%20TimeZone=UTC
    username: lms_user
    password: lms_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8081